services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_service
    environment:
      DB_HOST: postgres_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: appdb
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data: