# Generated by Django 5.1.7 on 2025-03-26 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id_ride', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('en-route', 'En-Route'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], default='en-route', max_length=255)),
                ('pickup_latitude', models.DecimalField(decimal_places=7, max_digits=12, null=True)),
                ('pickup_longitude', models.DecimalField(decimal_places=7, max_digits=12, null=True)),
                ('dropoff_latitude', models.DecimalField(decimal_places=7, max_digits=12, null=True)),
                ('dropoff_longitude', models.DecimalField(decimal_places=7, max_digits=12, null=True)),
                ('pickup_time', models.DateTimeField()),
                ('id_driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('id_rider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
