# Generated by Django 5.1.7 on 2025-03-27 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rideevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideevent',
            name='id_ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_events', to='core.ride'),
        ),
    ]
